- label: "Home"
  url: "/"
- label: "Who We Are"
  url: "/who-we-are"
- label: "Calendar"
  url: "/calendar"
- label: "Gallery"
  url: "/gallery"
- label: "Contact Us"
  url: "/contact"
#- label: "Forums"
#  url: "/forums"
