- label: "Home"
  url: "/"
- label: "Who We Are"
  url: "/who-we-are"
- label: "Calendar"
  url: "/calendar"
- label: "Photos"
  url: "/photo_sets"
- label: "Contact"
  url: "/contact"
- label: "Forums"
  url: "/forums"
